import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  containerMobile: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: 'black',
    borderWidth: 2,
    width: '100%',
    backgroundColor: '#1f1f1f',
  },
  containerWeb: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: 'black',
    borderWidth: 2,
    width: '100%',
    backgroundColor: '#1f1f1f',
  },
  homePageMobile: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    maxWidth: 800,
    borderColor: 'black',
    borderWidth: 2,
    backgroundColor: '#000000',
    paddingTop: 16,
  },
  homePageWeb: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    maxWidth: 800,
    borderColor: 'black',
    borderWidth: 2,
    backgroundColor: '#000000',
    paddingTop: 88,
  },
  triviaContent: {
    alignItems: 'center',
    flexDirection: 'column',
    width: '100%',
  },
  aiHintContainer: {
    paddingTop: 20,
    marginBottom: 20,
  },
  hintInfo: {
    paddingTop: 20,
    textAlign: 'center',
  },
  infoText: {
    color: '#fff',
    fontSize: 24,
    letterSpacing: 2.8,
  },
  // answerList: {
  //   color: '#fff',
  //   textAlign: 'center',
  //   textAlignVertical: 'center',
  //   overflow: 'visible',
  //   fontSize: 32,
  //   width: '100%',
  // },
  // answerListView: {
  //   flexDirection: 'column',
  //   alignItems: 'center',
  //   justifyContent: 'space-evenly',
  //   borderWidth: 1,
  //   borderBottomColor: '#fff',
  //   color: '#fff',
  //   textAlign: 'center',
  //   textAlignVertical: 'center',
  //   paddingVertical: 16,
  //   overflow: 'visible',
  //   marginBottom: 18,
  //   fontSize: 32,
  //   width: '60%',
  // },
  // answerContainer: {
  //   alignItems: 'center',
  //   width: '100%',
  //   paddingVertical: 28,
  //   paddingHorizontal: 32,
  // },
  inputViewMobile: {
    paddingVertical: 22,
    position: 'absolute',
    bottom: 0,
    alignSelf: 'center',
  },
  inputViewWeb: {
    paddingVertical: 22,
    position: 'absolute',
    bottom: 0,
    alignSelf: 'center',
  },
  input: {
    backgroundColor: '#000000',
  },
});
